"""The generated MCP tool reference (docs/mcp/tools.md) is complete and free of drift."""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "gen_mcp_reference.py"
COMMITTED = ROOT / "docs" / "mcp" / "tools.md"
TOOLS = (
    "preview_image",
    "preview_image_grid",
    "preview_image_bboxes",
    "preview_image_keypoints",
    "preview_image_polygons",
    "preview_image_segmentation",
    "preview_video",
    "preview_video_grid",
    "clip_audio",
    "color_from_text",
    "rotated_bbox_to_polygon",
    "normalize_coordinates",
    "denormalize_coordinates",
)


def run(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, str(SCRIPT), *args], capture_output=True, text=True, check=False, cwd=ROOT)


def test_generated_reference_lists_every_tool_and_matches_committed_file(tmp_path):
    out = tmp_path / "tools.md"
    result = run("--output", str(out))
    assert result.returncode == 0, result.stderr
    text = out.read_text(encoding="utf-8")
    assert re.findall(r"^## (\w+)$", text, re.MULTILINE) == list(TOOLS)
    assert "--8<--" not in text, "spec text is inlined, not included at build time"
    assert re.search(r"^### Goal$", text, re.MULTILINE), "spec headings are demoted to ###"
    assert text.count("### Goal") == 11, "13 tools, 11 spec files: a shared spec is inlined once"
    assert "shared with [`preview_video`](#preview_video)" in text
    assert text.startswith("<!-- generated by scripts/gen_mcp_reference.py")
    assert text.endswith("\n") and not text.endswith("\n\n")
    assert not any(line != line.rstrip() for line in text.splitlines())
    assert text == COMMITTED.read_text(encoding="utf-8"), "docs/mcp/tools.md is stale: run `just docs-gen`"


def test_check_mode_fails_on_drift(tmp_path):
    stale = tmp_path / "tools.md"
    stale.write_text(COMMITTED.read_text(encoding="utf-8").replace("## preview_image\n", "## preview_picture\n"))
    result = run("--check", "--output", str(stale))
    assert result.returncode == 1
    assert "run `just docs-gen`" in result.stdout
    assert "-## preview_picture" in result.stdout

    fresh = run("--check", "--output", str(COMMITTED))
    assert fresh.returncode == 0, fresh.stdout


def test_every_spec_carries_the_snippet_sections():
    for spec in (ROOT / ".agents" / "knowledge" / "spec").glob("*.md"):
        text = spec.read_text(encoding="utf-8")
        sections = ("user",) if spec.name == "mcp-overview.md" else ("user", "user2")
        for name in sections:
            assert f"<!-- --8<-- [start:{name}] -->" in text, f"{spec.name} lacks [start:{name}]"
            assert f"<!-- --8<-- [end:{name}] -->" in text, f"{spec.name} lacks [end:{name}]"
