"""Generate docs/mcp/tools.md from the live annotools MCP server.

The page lists every tool in a fixed order with its description, a parameter table derived from the
tool's ``inputSchema``, and the user-facing sections of the tool's spec (``.agents/knowledge/spec/<file>.md``,
``pymdownx.snippets`` sections ``user`` and ``user2``) inlined with their headings demoted one level.
The output is deterministic so the committed file can be checked for drift against both the server and
the spec prose.

Usage:
    uv run scripts/gen_mcp_reference.py            # write docs/mcp/tools.md
    uv run scripts/gen_mcp_reference.py --check    # exit 1 when the committed file is stale
    uv run scripts/gen_mcp_reference.py --output PATH [--check]
"""

import argparse
import asyncio
import difflib
import json
import re
import sys
from pathlib import Path

from fastmcp import Client

from annotools.mcp.server import mcp

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "mcp" / "tools.md"
SPEC_DIR = ROOT / ".agents" / "knowledge" / "spec"
HEADER = "<!-- generated by scripts/gen_mcp_reference.py — do not edit -->"
SECTIONS = ("user", "user2")
MARKER = re.compile(r"^<!--\s*--8<--\s*\[(start|end):([a-z][-_0-9a-z]*)\]\s*-->$")
SCALARS = {"integer": "int", "number": "float", "string": "str", "boolean": "bool"}

# Tool → spec file (relative to SPEC_DIR); one spec may cover several tools.
TOOLS: dict[str, str] = {
    "preview_image": "preview-image.md",
    "preview_image_grid": "preview-image-grid.md",
    "preview_image_bboxes": "preview-image-bboxes.md",
    "preview_image_keypoints": "preview-image-keypoints.md",
    "preview_image_polygons": "preview-image-polygons.md",
    "preview_image_segmentation": "preview-image-segmentation.md",
    "preview_video": "preview-video.md",
    "preview_video_grid": "preview-video.md",
    "clip_audio": "clip-audio.md",
    "color_from_text": "color-from-text.md",
    "rotated_bbox_to_polygon": "rotated-bbox-to-polygon.md",
    "normalize_coordinates": "coordinates.md",
    "denormalize_coordinates": "coordinates.md",
}

INTRO = """# MCP tools

Every tool the `annotools` MCP server exposes, in the order an annotation session usually needs them.
Coordinates are normalized 0.0-1.0 relative to the uncropped source; shared parameter groups, metadata
keys, and error rules are in the [overview](index.md). The parameter tables come from the server's tool
schemas; the text below each table is the tool's specification."""


def flatten_type(schema: dict, defs: dict) -> str:
    """Render a JSON-schema fragment as a Markdown type expression.

    Each alternative is its own code span joined by an escaped pipe, so the cell renders in both GitHub
    Flavored Markdown and Python-Markdown (which shows ``\\|`` literally inside a code span).
    """
    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        return flatten_type(defs[name], defs) if name in defs else f"`{name}`"
    if "anyOf" in schema:
        parts = [flatten_type(s, defs) for s in schema["anyOf"] if s.get("type") != "null"]
        if any(s.get("type") == "null" for s in schema["anyOf"]):
            parts.append("`null`")
        return " \\| ".join(parts)
    if "enum" in schema:
        return " \\| ".join(f"`{json.dumps(v)}`" for v in schema["enum"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " \\| ".join(f"`{k}`" for k in kind)
    if kind == "array":
        if "prefixItems" in schema:
            return "`[" + ", ".join(plain_type(s, defs) for s in schema["prefixItems"]) + "]`"
        if "items" in schema:
            return f"`array[{plain_type(schema['items'], defs)}]`"
        return "`array`"
    if kind == "object":
        if "properties" in schema:
            return "`object{" + ", ".join(schema["properties"]) + "}`"
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"`object{{string: {plain_type(extra, defs)}}}`"
        return "`object`"
    return f"`{SCALARS.get(kind, kind or 'any')}`"


def plain_type(schema: dict, defs: dict) -> str:
    """Type expression without code spans, for nesting inside one (alternatives joined with ``or``)."""
    return flatten_type(schema, defs).replace("`", "").replace(" \\| ", " or ")


def cell(text: str) -> str:
    """Make prose safe for one Markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def description_of(prop: dict) -> str:
    """A parameter's description, else the first line of its items' or non-null branch's description."""
    if prop.get("description"):
        return prop["description"]
    branches = [prop.get("items", {}), *[s for s in prop.get("anyOf", []) if s.get("type") != "null"]]
    for candidate in branches:
        if candidate.get("description"):
            # Nested models document themselves in reST-style docstrings; ``x`` becomes `x`.
            return candidate["description"].strip().splitlines()[0].replace("``", "`")
    return ""


def parameter_table(schema: dict) -> list[str]:
    defs = schema.get("$defs", {})
    required = set(schema.get("required", []))
    rows = ["| Parameter | Type | Default | Required | Description |", "|---|---|---|---|---|"]
    for name, prop in schema.get("properties", {}).items():
        default = f"`{json.dumps(prop['default'])}`" if "default" in prop else "—"
        rows.append(
            f"| `{name}` | {flatten_type(prop, defs)} | {default} | "
            f"{'yes' if name in required else 'no'} | {cell(description_of(prop))} |"
        )
    return rows


def spec_sections(spec: str) -> list[str]:
    """The ``user`` and ``user2`` sections of a spec, ``##`` headings demoted to ``###``."""
    lines = (SPEC_DIR / spec).read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    for section in SECTIONS:
        inside = found = False
        for line in lines:
            m = MARKER.match(line.strip())
            if m and m.group(2) == section:
                if m.group(1) == "start":
                    inside = found = True
                    continue
                inside = False
                break
            if m:
                continue
            if inside:
                out.append("#" + line if line.startswith("## ") else line)
        if not found:
            raise SystemExit(f"ERROR: {spec} has no snippet section '{section}' (see spec-format.md)")
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)).strip().splitlines()


def render(tools: list) -> str:
    by_name = {t.name: t for t in tools}
    missing = set(TOOLS) - set(by_name)
    extra = set(by_name) - set(TOOLS)
    if missing or extra:
        raise SystemExit(
            f"ERROR: tool list drift — missing from server: {sorted(missing)}, not in TOOLS map: {sorted(extra)}"
        )
    out = [HEADER, "", INTRO]
    first_tool_for: dict[str, str] = {}
    for name, spec in TOOLS.items():
        if not (SPEC_DIR / spec).is_file():
            raise SystemExit(f"ERROR: spec file not found for {name}: {SPEC_DIR / spec}")
        tool = by_name[name]
        out += ["", f"## {name}", ""]
        if tool.description:
            out += [*tool.description.strip().splitlines(), ""]
        out += [*parameter_table(tool.inputSchema), ""]
        if spec in first_tool_for:
            shared = first_tool_for[spec]
            out.append(f"Specification: shared with [`{shared}`](#{shared}) (`.agents/knowledge/spec/{spec}`).")
        else:
            first_tool_for[spec] = name
            out += spec_sections(spec)
    return "\n".join(line.rstrip() for line in out).rstrip() + "\n"


async def list_tools() -> list:
    async with Client(mcp) as client:
        return await client.list_tools()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="compare with the committed file instead of writing")
    parser.add_argument("--output", type=Path, default=OUTPUT, help=f"target file (default: {OUTPUT})")
    args = parser.parse_args()
    text = render(asyncio.run(list_tools()))
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
        if current == text:
            print(f"{args.output} is up to date.")
            return 0
        sys.stdout.writelines(
            difflib.unified_diff(
                current.splitlines(keepends=True), text.splitlines(keepends=True), "committed", "generated"
            )
        )
        print(f"ERROR: {args.output} is stale; run `just docs-gen` and commit the result.")
        return 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
